version: '3'
services:
  app:
    build: .
    depends_on: 
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  